### ISSUE TITLE
在博客中插入bookdown页面

### ISSUE THREAD

**Issue by qiushiyan** [JiaxiangBU/learn_rmd#13]
请教一下博主，在个人网站里面是怎么链接 bookdown 页面的呢？比如像这种笔记的嵌入 https://jiaxiangli.netlify.com/2020/02/05/reading-notes-israeli-palestinian-conflict-cookbook/

**Comment by JiaxiangBU** [comment]
@enixam 加入一下 `iframe` 即可，博客项目没有开源，我把源代码复制一下给你。

```markdown
---
title: 巴以冲突 学习笔记
author: 李家翔
date: '2020-02-05'
slug: reading-notes-Israeli-Palestinian-conflict-cookbook
categories:
  - book
tags:
  - book
---
<iframe src="https://jiaxiangbu.github.io/reading_notes/Israeli-Palestinian-conflict/cookbook.html" width="100%" height="800px"></iframe>
```

然后，这个的实现是靠`blogdown`完成的，其中 iframe 的链接是靠`bookdown`实现的。
如果你不知道 bookdown 怎么实现的话，你可以参考这个项目，https://github.com/JiaxiangBU/nintendo_switch_mario

如有问题，我们再沟通。

**Comment by qiushiyan** [comment]
好的，感谢~

**Comment by uptowndat777777** [comment]
Hello, Compliment of the day, how are you today ? i am Happy to get together with you,My name is Serach , I'm a military medical nurse from israel. Please let not my profession, race or nationality inch your mind, I have gone across your profile and became interested in you, we can be good friends, contact me through my private email address/  //abelmans@aol.com   ////
